### ISSUE TITLE
Docker Volume Portability - Save Configs in data directory

### ISSUE THREAD

**Issue by jxsl13** [mrvautin/openKB#265]
Hey, because I use Docker and would really love port openKB easily with all my settings, it would be great if openKB would create the config files on the first startup in the same folder, where all of the *.db files are saved(data folder), after checking if there already is a config file there.

This would make openKB even more portable than it already is.
I set up openKB using this small script:
```bash
#!/bin/bash

# pull repo
git clone https://github.com/mrvautin/openKB.git && cd openKB
# build container
docker build -t mrvautin/openkb .

# remove git repository
cd ..
rm -r openKB

# first run only accessible from localhost
docker run --name=openkb -p 127.0.0.1:4444:4444 -v /var/lib/openKB:/var/openKB/data mrvautin/openkb:latest &

# stop
docker stop openkb

#run start normally
docker start openkb
```

the only problem is that when changing my servers/hosters the actual config file is sadly still within the container and not saved in the data folder /var/openKB/data, which is mounted and accessible from outside the container in /var/lib/openKB
For now the only stuff that is portable is everything within the data folder.

Moreover everything that is being added by the user should be saved in a subfolder of data, like images, custom themes and so on.

**Comment by mateodelnorte** [comment]
Just use docker-compose or docker stacks to mount a volume for whatever particular folder you want to re-use between container instances: 

docker-compose:
```
version: "3.3"

services:

  openkb:
    image: wachiwi/openkb
    restart: always
    ports:
      - 4444:4444
    volumes:
      - .data/data:/var/openKB/data
      - .data/uploads:/var/openKB/public/uploads

```

docker swarm stack:
```
version: "3.3"

services:

  openkb:
    image: wachiwi/openkb
    restart: always
    networks:
      - proxy
    volumes:
      - data:/var/openKB/data
      - uploads:/var/openKB/public/uploads

volumes:

  data:
    driver: cloudstor:aws

  uploads:
    driver: cloudstor:aws
```

I'm guessing you won't need the uploads directory if you're using mongo. Perhaps you won't need either.
